--zad1a
create table A6_LRS
(GEOM MDSYS.SDO_GEOMETRY);
--zad1b
INSERT INTO A6_LRS
SELECT A.GEOM
FROM STREETS_AND_RAILROADS A, MAJOR_CITIES B
WHERE SDO_RELATE(A.GEOM, SDO_GEOM.SDO_BUFFER(B.GEOM, 10, 1, 'unit=km'), 'mask=ANYINTERACT') = 'TRUE' 
    AND B.CITY_NAME = 'Koszalin';
--zad1c
SELECT ROUND(SDO_GEOM.SDO_LENGTH(GEOM, 1, 'unit=km'), 7) AS DISTANCE, ST_LINESTRING(GEOM).ST_NUMPOINTS() AS ST_NUMPOINTS
FROM A6_LRS;
--zad1d
UPDATE A6_LRS SET GEOM = SDO_LRS.CONVERT_TO_LRS_GEOM(GEOM, 0, SDO_GEOM.SDO_LENGTH(GEOM, 1, 'unit=km'));
--zad1e
INSERT INTO USER_SDO_GEOM_METADATA
VALUES ('A6_LRS','GEOM',MDSYS.SDO_DIM_ARRAY(MDSYS.SDO_DIM_ELEMENT('X', 12.603676, 26.369824, 1),
            MDSYS.SDO_DIM_ELEMENT('Y', 45.8464, 58.0213, 1),
            MDSYS.SDO_DIM_ELEMENT('M', 0, 300, 1)),8307);
--zad1f
CREATE INDEX A6_LRS_INDEX ON A6_LRS(GEOM) INDEXTYPE IS MDSYS.SPATIAL_INDEX;

--zad2a
select SDO_LRS.VALID_MEASURE(GEOM, 500) VALID_500
from   A6_LRS;

--zad2b
select SDO_LRS.GEOM_SEGMENT_END_PT(GEOM) END_PT
from   A6_LRS;
--zad2c
select SDO_LRS.LOCATE_PT(GEOM, 150, 0) KM150 from A6_LRS;

--zad2d
select SDO_LRS.CLIP_GEOM_SEGMENT(GEOM, 120, 160) CLIPED from A6_LRS;

--zad2e
SELECT SDO_LRS.GET_NEXT_SHAPE_PT(A6.GEOM, SDO_LRS.PROJECT_PT(A6.GEOM, C.GEOM)) AS WJAZD_NA_A6
FROM A6_LRS A6, MAJOR_CITIES C WHERE C.CITY_NAME = 'Slupsk';

--zad2f
select ROUND(SDO_GEOM.SDO_LENGTH(
SDO_LRS.OFFSET_GEOM_SEGMENT(A6.GEOM, M.DIMINFO, 50, 200, 50,'unit=m') , 1, 'unit=km'), 7) AS koszt
from   A6_LRS A6, USER_SDO_GEOM_METADATA M 
where M.TABLE_NAME = 'A6_LRS' 
    and M.COLUMN_NAME = 'GEOM'
